[package]
name = "none-as-undefined"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minijinja = { path = "../../minijinja" }
serde = { version = "1.0.130", features = ["derive"] }
