[workspace]
members = ["minijinja", "tools/*", "examples/*", "benchmarks", "minijinja-autoreload"]
exclude = ["examples/README.md", "tools/README.md"]

[profile.release]
debug = true

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
