[package]
name = "minijinja"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "a powerful template engine for Rust with minimal dependencies"
homepage = "https://insta.rs/"
repository = "https://github.com/mitsuhiko/minijinja"
keywords = ["jinja", "jinja2", "templates"]
readme = "README.md"

[features]
speedups = ["memchr"]

# provides access to the unstable machinery
unstable_machinery = []

[dependencies]
serde = "1.0.130"
memchr = { version = "2.4.1", optional = true }

[dev-dependencies]
insta = { version = "1.7.2", features = ["glob"] }
serde_json = "1.0.68"
serde_yaml = "0.8.20"
