[workspace]
members = ["minijinja", "examples/*", "benchmarks", "minijinja-*"]
exclude = ["examples/README.md"]

[profile.release]
debug = true

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
