[workspace]
members = ["cargo:minijinja-cli"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.4"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc", "i686-unknown-linux-gnu", "i686-unknown-linux-musl", "i686-pc-windows-msvc"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Build only the required packages, and individually
precise-builds = true
# Path that installers should place binaries in
install-path = ["$MINIJINJA_CLI_INSTALL_DIR/bin", "~/.local/bin"]
# Whether to install an updater program
install-updater = false

[dist.dependencies.apt]
gcc-aarch64-linux-gnu = { version = '*' }
gcc-i686-linux-gnu = { version = '*' }
gcc-arm-linux-gnueabi = { version = '*' }
gcc-arm-linux-gnueabihf = { version = '*' }
musl-tools = { version = '*' }
