[package]
name = "minijinja"
version = "0.8.1"
edition = "2018"
license = "Apache-2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "a powerful template engine for Rust with minimal dependencies"
homepage = "https://github.com/mitsuhiko/minijinja"
repository = "https://github.com/mitsuhiko/minijinja"
keywords = ["jinja", "jinja2", "templates"]
readme = "README.md"

[package.metadata.docs.rs]
features = ["source", "json", "urlencode"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["builtin_filters", "builtin_tests", "builtin_functions", "sync"]
sync = []
speedups = ["memchr", "v_htmlescape"]
source = ["self_cell"]
builtin_filters = []
builtin_tests = []
builtin_functions = []
json = ["serde_json"]
urlencode = ["percent-encoding"]

# provides access to the unstable machinery
unstable_machinery = []

[dependencies]
serde = "1.0.130"
memchr = { version = "2.4.1", optional = true }
v_htmlescape = { version = "0.14.1", optional = true }
self_cell = { version = "0.10.1", optional = true, features = ["old_rust"] }
serde_json = { version = "1.0.68", optional = true }
percent-encoding = { version = "2.1.0", optional = true }

[dev-dependencies]
insta = { version = "1.7.2", features = ["glob"] }
serde_json = "1.0.68"
serde_yaml = "0.8.20"
