[package]
name = "build-script"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
minijinja = { path = "../../minijinja", default-features = false, features = ["serde", "builtins"] }
