[package]
name = "function-using-async"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axominijinja = { version = "2.4.0", path = "../../minijinja" }
tokio = { version = "1.37.0", features = ["macros", "rt", "rt-multi-thread"] }
